### ISSUE TITLE
Oneplus one 64GB very slow boot (Including recovery)

### ISSUE THREAD

**Issue by kdb424** [offensive-security/kali-nethunter#404]
Another slow boot issue, this time on a oneplus one. I have tried several base roms, the most recent (currently installed) is the latest stock rom rooted, then installed nethunter. Using latest twrp at the time of this post, and tried older versions also. Wallpaper did not set, recovery can take literally minutes to boot, rom sometimes locks at boot. Didn't have any issues before installing. Would provide logcats, but they seem to not want to allow me to access with ADB. Suggestions on gettings logs would be great, and I'll get them.

Steps to reproduce
1. Unlock bootloader
2. Flash all stock files one by one (tried flashall.sh also) Complete success.
3. Run stock for a day works perfect
4. Flash TWRP
5. Factory reset in recovery
6. Flash latest nethunter
7. Boot fine and update everything
8. Hard reboot and massively slow device even in recovery. Powered off for 10 minutes to see if that was possibly an issue.

Steps I'm going to try to see if it helps.
1. Flash AK kernel and probably lose features
2. Manually trim the filesystem if I can get in
3. Install multirom and move to secondary slot and just deal with it
4. Hope someone has a better solution

**Comment by binkybear** [comment]
@kdb424 - Thanks for the good formatted issue.  I use the OnePlus1 daily for testing but just switched to CM13 on it.  Can I ask you:

* Are you using CyangenOS (I assume so because flashall)?
* Did you use the latest kernel build from the github repo?

It wouldn't hurt to try AK kernel to see if it speeds things up.  The kernel is based off AK kernel so I'm not sure it will help a  whole lot.  If you used the zip files from the official site they are a little outdated now and you may be better off using the builds form this repo or from https://idlekernel.com/nethunter/nightly/.

**Comment by kdb424** [comment]
I was using CyanogenOS, and just endud up switching to CM13 vanilla after posting. I ended up trying AK kernel and it wouldn't boot at all, hense the switch. I used the downloads from the official site yes. I'll consider giving that a shot again. Any chance you know if it supports multirom, CM 13 official that is, so I can test easier with less time in between? Backups are painfully slow when I run into this.

**Comment by binkybear** [comment]
The latest CM13 kernel does not have kexec patch so it will not work multirom.  I will def add it in update though.

**Comment by kdb424** [comment]
Fantastic. I should have time to test again in a few days. A search of the web showed me I'm not the only one with this issue, so hopefully it can get sorted. Very much appreciated.

**Comment by binkybear** [comment]
Whoops didn't meant to close.

In testing the boot time is VERY slow and appears to be slowed down by something in ramdisk (before it get's to boot animation).  It took a couple of minutes to get it up and running.  At the moment I do not know what's causing the slow down (we don't modify ramdisk).

**Comment by kdb424** [comment]
Ok, sorry to hear that but glad it's not just me. If there is any testing that I can do, let me know.

**Comment by binkybear** [comment]
No worries.  I tested out y-cable today, and while it does charge, it doesn't seem to recognize wlan1.  I'm not sure what changed (worked fine in lollipop).  So I will work on it more this weekend hopefully.

**Comment by kdb424** [comment]
To ensure that I get the same results as you, what base ROM are you using so my testing is actually useful to you? I'll start pulling sources to compile and stay up to date.

**Comment by binkybear** [comment]
I'm using a CM13 nightly with a build date of 9 March.  Feel free to try a newer version.  I just merged latest CM13 branch kernel updates.

**Comment by kdb424** [comment]
Ok, I'm running the build from the 15th, so I'll test Monday and keep up on commit changes in the mean time. Can't wait to get this going. That kernel patch will be great for those that want to seperate work and play.

**Comment by kdb424** [comment]
Not getting a boot unfortunately. Running the snapshot you based your latest commit on, factory reset, boot once, ran build with flags "-d oneplus1 -m"

**Comment by jcadduono** [comment]
You can simply remove supersu.zip from the installer and it should proceed with the install.
It actually isn't necessary on CM13 since you can enable su from dev options.
I'm also running into strange issues with SuperSU in system install mode on the latest M and N.
I'll see what Chainfire knows.

**Comment by kdb424** [comment]
Awesome. Thanks for the update. I pulled the repo changes, made an installer, and still having the inability to use the device as HID thus far. CM13 snapshot, installed kernel, nosu and full kali. Other strange issue I have is the "Error Launching Intent: Install Android Terminal" all of a sudden. Uninstalled completely and installed packages from the repo directly on the phone, and still having the issue. That fixed it before. Sorry for all of the problems. The nosu is a very useful addition. Thanks for everything.
